export const GET_WEATHER_BEGIN = 'GET_WEATHER_BEGIN';
export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS';
export const GET_WEATHER_ERROR = 'GET_WEATHER_ERROR';

export const CHECK_BREAKPOINT = 'CHECK_BREAKPOINT';
